# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Søren Øxenhave'
tagline:             'Tech Lead at TimeLog'
description:         'I''m a Tech Lead at <a href="http://www.timelog.com" target="_blank">TimeLog</a>. I help the team perform and ensures good code structures.'
url:                 http://www.oexenhave.dk
baseurl:             '/'
paginate:            5
excerpt_separator:  <!--more-->
highlighter:        rouge
repository:         oexenhave/oexenhave.github.io

# About/contact
author:
  name:              Søren Øxenhave
  url:               https://twitter.com/oexenhave
  email:             soeren@oexenhave.dk

# Custom vars
version:             1.0.0

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, .git]

gems: [rubygems,jekyll-paginate, wdm,rouge]

# bash on ubuntu on Windows 10...
# https://www.tiernanotoole.ie/2016/04/11/installing-jekyll-on-bash-on-ubuntu-on-windows.html
# 1. sudo apt-get update
# 2. sudo apt-get install nodejs
# 3. sudo apt-get install git 
# 4. sudo apt-get install ruby2.0
# 5. ruby -v # should be v2
# 6. sudo gem install bundler
# 6.1 sudo apt-get install zlib1g-dev # if zlib is missing; necessary for building libxml2 *** extconf.rb failed ***
# 7. bundle install
# 8. sudo ln /usr/local/bin/jekyll /usr/bin/jekyll
# 9. jekyll build
# 10. jekyll s --no-watch
###
# sudo apt-get install jekyll
# sudo apt-get install rubygems
# sudo apt-get install jekyll-paginate
# sudo apt-get install rouge